[[language]]
name = "rust"
language-servers = [{ name = "rust-analyzer" }]
auto-format = false

[[language]]
name = "haskell"
language-servers = [{ name = "haskell-language-server" }]

[[language]]
name = "cpp"
language-servers = [{ name = "clangd" }]
indent = { tab-width = 4, unit = "    " }
auto-format = false

[[language]]
name = "python"
language-servers = [{ name = "pylsp" }]

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true
