[[language]]
name = "rust"
language-servers = [{ name = "rust-analyzer" }]

[[language]]
name = "haskell"
language-servers = [{ name = "haskell-language-server" }]

[[language]]
name = "c"
language-servers = [{ name = "clangd" }]

[language-server.clangd.config.clangd]
config = { provideFormatter = false }

[[language]]
name = "python"
language-servers = [{ name = "pylsp" }]

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[[language]]
name = "rust"
language-servers = [{ name = "rust-analyzer" }]
